### PR TITLE
DO NOT MERGE: various directory structure prototypes

### PR DESCRIPTION
**Pull request by IgorMinar**
each commit is a new proposal. commit messages contain listing generated via `tree`

### CODE REVIEW

**Comment by IgorMinar** [comment]
@juleskremer asked me why is it important to be able to distinguish the routable directories from non-routable ones. the answer is - 1/ it helps understand the project structure, 2/ on large teams various directories will be owned by different teams 3/ the directory structure should make it obvious where the boundaries of lazy-loaded code are so that developers don't cross them accidentally.

to visualize where the lazy-loading boundaries in this app should be I drew the following sketch:

houston-lazy-loading

each unit will be bundled separately by the build system (until we have http2) and each unit needs to be loaded via `System.import` rather than `import ... from`. if developers use `import` to cross the boundary they'll get an error either during compilation or at runtime. if we don't make it easy for them to undertand where the boundaries are, they'll be confused and won't know when to use `import` vs `System.import`.

**Comment by johnpapa** [comment]
I;d like to understand this better. What do you mean by crossing boundaries?

And can you explain why those 3 points are important? I'm hear you, but I don't see the consequence of each.

**Comment by IgorMinar** [comment]
@johnpapa I expanded my previous comment https://github.com/juleskremer/houston/pull/8#issuecomment-200099652. is that better? or is it still not clear?

**Comment by wardbell** [comment]
Re: why is it important to be able to distinguish the routable directories from non-routable ones

"3/ the directory structure should make it obvious where the boundaries of lazy-loaded code are so that developers don't cross them accidentally" sells it for me.

I think I'd want that clarity even if I wasn't lazy loading.

_I'm not commenting on the chosen manner of distinction, only the value of some distinction._

**Comment by johnpapa** [comment]
Thanks. is one of the cases you are trying to safeguard against is when someone `import * from 'a/b/c` where `b` may be a component router ?

**Comment by wardbell** [comment]
I'm still feeling that the folder structure is over-granular. In most cases I'd stop at the routable directory boundary and be flat below that until the number of files told me to do otherwise.

I still don't understand why we have promoted so many classes. For example, why is there a promoted `Developers` directory that is also deep. Is it shared across other features?

As a member of the team developing the `Developers` feature I'm obliged to look in two very different places to support my project. I'm also driven to give them different dev-cycles because the outer shared folders are likely on a different cadence (and SLA) then the feature folders.

In general, I strive to minimize the shared stuff. It's usually generic stuff like loggers.  I don't expect to see `Developers` stuff hanging out at a high level in my app structure.

What am I missing?

**Comment by juleskremer** [comment]
@IgorMinar can correct my assumptions if I'm wrong:

@wardbell I believe your first statement is accurate:  Ignore that Houston is currently in a state where *you* (or I) would flatten the Developers route and pretend that there are indeed a threshold # of files wherein you would want to split them out.  That is the use case we are exploring against (vs. what you see as factual in Houston today).  When a developer users ng new myproject they aren't going to get a 3 level deep hierarchy of blank folders.

My expectation of development teams is that "Developers" might be owned by one team including features of developers.  Is this not the case in your experience?  I would expect that TeamA writes Developers and maybe TeamB is writing Communities and those should have interfaces to each other where necessary.  I am still confused at how "mutual routing" (I have no idea the real name for this) works.  For example:

Developer Detail is a feature of Developers but could also be (and is) routed to from Events, Communities (and pretty much anything else that is going to go into this app since the individual developer is central to the purpose of the app).  How would that be handled/identified in this scenario?

**Comment by Brocco** [comment]
@IgorMinar by having models/services outside of the route folder structure (i.e. `[communities]` + `communities` **or** `communities` + `communities-model`) doesn't that hinder the ability to promote components? At the very least it would complicate as there would be two folders that would need promoted as it is not contained under the component directory.

**Comment by IgorMinar** [comment]
@Brocco this is just a problem with the Houston app - currently all models/data-services must be at the top level because of how ngrx/store is used.

This is unfortunate because it pushes most of the reusable services to the top level of the app and doesn't allow me to show how these features could be contained within the route directory.

This also answers @wardbell's questions - most of the stuff is at the top level because of the current data-store design, which I'm not keen on, but during all of the refactorings I've done on houston I avoided changing the content of the files - I've been focused only on cleaning up the structure and file layout.

**Comment by johnpapa** [comment]
Thanks for the explanation @IgorMinar .

Perhaps removing the store for now and focusing on how the CLI can work with an app might make help achieve your goals.

We can always look at ngrx after, as it is interesting.

**Comment by johnpapa** [comment]
Re: distinguishing ... I agree that would be nice to help folks just by looking at it. I'm torn on the prefix convention using a special character. If one is chosen it should work in all OS variations, web servers, and tooling and be easy to read. As a general rule we can try to follow, I propose that making it distinguishable should only come if we don't also introduce a new confusion. 

I agree with you that the need for top level store aspects are not ideal. A lot of apps I have been involved with have features that contain services for their own data. Then shared top level services that are for everyone. In the A1 style guide we referred to these top level services as `core services`.  This image shows this https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md#style-y165 It may be helpful to pull the store for now, so we can focus on the issues you are working on first. Then circle back to a store at a later time. We should allow for it, but not design for it.

This would also remove the need for the duplication of the service/model for each component feature (e.g. `developer-model`). 

Instead of a top level pipe, I propose a top level `shared` or `common` folder (pick a name). This would contain all shared A2 assets across the app.

I propose that the CLI should allow the developer to choose if s/he wants to nest a new component in a new folder or place it alongside other components. For example, if the folder structure `app/developers` exists and a user goes to create a new component there, it could allow the user to choose to place the component right there or in a nested folder. If this is out of scope I suggest having the CLI create it at the flatter level. A dev can always refactor if it gets too crowded.

**Comment by filipesilva** [comment]
Prototypes that do not group common stuff in a module seem impractical. They impose convoluted naming schemes on feature modules/routes folders, and learning a specific nomenclature for directory structures is another learning speedbump. I also think it looks a bit ugly.

The `_` (or `_common`/`common`/`shared`) folder seems to be a better solution.

Prototypes structures are also not including css files, these would add extra files that would further the argument of putting routes within folders. 

I understand the use and need of `index.ts` but find it hard to justify that in any of these structures they represent almost 1/4th of the total files. I don't have a better option to propose though.

I would also like to bring up the question of SCSS/LESS modules and dependency management. This complicates directory structures. Consider using bootstrap in SCSS: each component has a `.scss` file. and `soft depends` on bootstrap. 

If your module uses any bootstrap variable, for instance `$line-height`, or `$primary-color`, it now has a hard dependency on bootstrap that cannot be expressed in that component, but only on parent components, because that is how SCSS imports work.

This adds the equivalent of `index.js`, an `index.scss` to 'barrel up' scss files from child components and make them accessible to parent ones, so that all the connected SCSS structure has access to global and bootstrap default vars.

**Pull request closed without merging**
